# Generated by Django 4.1.2 on 2022-12-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variationmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
