# Generated by Django 4.1.2 on 2023-01-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_delete_variationmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='images',
            field=models.ImageField(blank=True, default='static/images/dash.png', upload_to='productimages'),
        ),
    ]
