# Generated by Django 4.1.2 on 2023-01-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_products_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='images',
            field=models.ImageField(blank=True, default='static/images/dash.png', upload_to='products'),
        ),
    ]
