# Generated by Django 4.1.2 on 2022-12-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupens',
            new_name='Coupon',
        ),
    ]
