# Generated by Django 4.1.2 on 2022-12-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_address_line_1_account_address_line_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/images/propic.png', upload_to='userprofile'),
        ),
    ]
