# Generated by Django 4.1.2 on 2022-12-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address_line_1',
            field=models.CharField(blank=True, default='fill the address', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='address_line_2',
            field=models.CharField(blank=True, default='fill the address', max_length=100),
        ),
    ]
