# Generated by Django 4.1.2 on 2022-12-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address_line_1',
            field=models.CharField(blank=True, default='Address line 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='address_line_2',
            field=models.CharField(blank=True, default='Address line 2', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(default='city', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(default='country', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.CharField(default='state', max_length=50),
        ),
    ]
