# Generated by Django 4.1.2 on 2022-12-18 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_shippingaddress_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
