# Generated by Django 4.1.2 on 2022-12-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_shippingaddress_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='default',
            new_name='is_default',
        ),
    ]
