# Generated by Django 4.1.2 on 2022-12-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='username',
            new_name='name',
        ),
    ]
