# Generated by Django 4.1.2 on 2022-12-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_rename_username_shippingaddress_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='email',
        ),
    ]
