# Generated by Django 4.1.2 on 2022-12-14 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_country_order_order_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='storage',
        ),
    ]
